if not PhreakDisplayFonts then return end
local revision = tonumber(string.sub("$Revision: 80300 $", 12, -3))
PhreakDisplayFonts.revision = (revision > PhreakDisplayFonts.revision) and revision or PhreakDisplayFonts.revision


-- -----
--   FONT
-- -----
PhreakDisplayFonts:Register("font", "Amaranth Bold", [[Interface\Addons\PhreakDisplayFonts\Fonts\Amaranth Bold.ttf]]) 
PhreakDisplayFonts:Register("font", "Amaranth", [[Interface\Addons\PhreakDisplayFonts\Fonts\Amaranth.ttf]]) 
PhreakDisplayFonts:Register("font", "Anonymous Bold", [[Interface\Addons\PhreakDisplayFonts\Fonts\Anonymous Bold.ttf]]) 
PhreakDisplayFonts:Register("font", "Anonymous", [[Interface\Addons\PhreakDisplayFonts\Fonts\Anonymous.ttf]]) 
PhreakDisplayFonts:Register("font", "Audiowide.", [[Interface\Addons\PhreakDisplayFonts\Fonts\Audiowide..ttf]]) 
PhreakDisplayFonts:Register("font", "Beware", [[Interface\Addons\PhreakDisplayFonts\Fonts\Beware.ttf]]) 
PhreakDisplayFonts:Register("font", "Bio Rhyme Bold", [[Interface\Addons\PhreakDisplayFonts\Fonts\Bio Rhyme Bold.ttf]]) 
PhreakDisplayFonts:Register("font", "Bio Rhyme", [[Interface\Addons\PhreakDisplayFonts\Fonts\Bio Rhyme.ttf]]) 
PhreakDisplayFonts:Register("font", "Bitter Bold", [[Interface\Addons\PhreakDisplayFonts\Fonts\Bitter Bold.ttf]]) 
PhreakDisplayFonts:Register("font", "Bitter", [[Interface\Addons\PhreakDisplayFonts\Fonts\Bitter.ttf]]) 
PhreakDisplayFonts:Register("font", "Caveat Bold", [[Interface\Addons\PhreakDisplayFonts\Fonts\Caveat Bold.ttf]]) 
PhreakDisplayFonts:Register("font", "Caveat", [[Interface\Addons\PhreakDisplayFonts\Fonts\Caveat.ttf]]) 
PhreakDisplayFonts:Register("font", "Cinzel Bold", [[Interface\Addons\PhreakDisplayFonts\Fonts\Cinzel Bold.ttf]]) 
PhreakDisplayFonts:Register("font", "Cinzel", [[Interface\Addons\PhreakDisplayFonts\Fonts\Cinzel.ttf]]) 
PhreakDisplayFonts:Register("font", "Comfortaa Bold", [[Interface\Addons\PhreakDisplayFonts\Fonts\Comfortaa Bold.ttf]]) 
PhreakDisplayFonts:Register("font", "Comfortaa", [[Interface\Addons\PhreakDisplayFonts\Fonts\Comfortaa.ttf]]) 
PhreakDisplayFonts:Register("font", "Comic Neue Bold", [[Interface\Addons\PhreakDisplayFonts\Fonts\Comic Neue Bold.ttf]]) 
PhreakDisplayFonts:Register("font", "Comic Neue", [[Interface\Addons\PhreakDisplayFonts\Fonts\Comic Neue.ttf]]) 
PhreakDisplayFonts:Register("font", "Coustard Bold", [[Interface\Addons\PhreakDisplayFonts\Fonts\Coustard Bold.ttf]]) 
PhreakDisplayFonts:Register("font", "Coustard", [[Interface\Addons\PhreakDisplayFonts\Fonts\Coustard.ttf]]) 
PhreakDisplayFonts:Register("font", "Doris Bold", [[Interface\Addons\PhreakDisplayFonts\Fonts\Doris Bold.ttf]]) 
PhreakDisplayFonts:Register("font", "Doris", [[Interface\Addons\PhreakDisplayFonts\Fonts\Doris.ttf]]) 
PhreakDisplayFonts:Register("font", "Emblem Bold", [[Interface\Addons\PhreakDisplayFonts\Fonts\Emblem Bold.ttf]]) 
PhreakDisplayFonts:Register("font", "Emblem", [[Interface\Addons\PhreakDisplayFonts\Fonts\Emblem.ttf]]) 
PhreakDisplayFonts:Register("font", "Exo Bold", [[Interface\Addons\PhreakDisplayFonts\Fonts\Exo Bold.ttf]]) 
PhreakDisplayFonts:Register("font", "Exo", [[Interface\Addons\PhreakDisplayFonts\Fonts\Exo.ttf]]) 
PhreakDisplayFonts:Register("font", "Gaegu Bold", [[Interface\Addons\PhreakDisplayFonts\Fonts\Gaegu Bold.ttf]]) 
PhreakDisplayFonts:Register("font", "Gaegu", [[Interface\Addons\PhreakDisplayFonts\Fonts\Gaegu.ttf]]) 
PhreakDisplayFonts:Register("font", "Galadar", [[Interface\Addons\PhreakDisplayFonts\Fonts\Galadar.ttf]]) 
PhreakDisplayFonts:Register("font", "Gentium Bold", [[Interface\Addons\PhreakDisplayFonts\Fonts\Gentium Bold.ttf]]) 
PhreakDisplayFonts:Register("font", "Hack Bold", [[Interface\Addons\PhreakDisplayFonts\Fonts\Hack Bold.ttf]]) 
PhreakDisplayFonts:Register("font", "Hack", [[Interface\Addons\PhreakDisplayFonts\Fonts\Hack.ttf]]) 
PhreakDisplayFonts:Register("font", "HookedUp", [[Interface\Addons\PhreakDisplayFonts\Fonts\HookedUp.ttf]]) 
PhreakDisplayFonts:Register("font", "Hot Pizza", [[Interface\Addons\PhreakDisplayFonts\Fonts\Hot Pizza.ttf]]) 
PhreakDisplayFonts:Register("font", "Just For Fun", [[Interface\Addons\PhreakDisplayFonts\Fonts\Just For Fun.ttf]]) 
PhreakDisplayFonts:Register("font", "LifeCraft", [[Interface\Addons\PhreakDisplayFonts\Fonts\LifeCraft.ttf]]) 
PhreakDisplayFonts:Register("font", "Lobster", [[Interface\Addons\PhreakDisplayFonts\Fonts\Lobster.ttf]]) 
PhreakDisplayFonts:Register("font", "Mutant Academy", [[Interface\Addons\PhreakDisplayFonts\Fonts\Mutant Academy.ttf]]) 
PhreakDisplayFonts:Register("font", "Oleo Script Bold", [[Interface\Addons\PhreakDisplayFonts\Fonts\Oleo Script Bold.ttf]]) 
PhreakDisplayFonts:Register("font", "Oleo Scriptr", [[Interface\Addons\PhreakDisplayFonts\Fonts\Oleo Scriptr.ttf]]) 
PhreakDisplayFonts:Register("font", "Porkys", [[Interface\Addons\PhreakDisplayFonts\Fonts\Porkys.ttf]]) 
PhreakDisplayFonts:Register("font", "Rikys Vampdator", [[Interface\Addons\PhreakDisplayFonts\Fonts\Rikys Vampdator.ttf]]) 
PhreakDisplayFonts:Register("font", "Roadway", [[Interface\Addons\PhreakDisplayFonts\Fonts\Roadway.ttf]]) 
PhreakDisplayFonts:Register("font", "Roboto Bold", [[Interface\Addons\PhreakDisplayFonts\Fonts\Roboto Bold.ttf]]) 
PhreakDisplayFonts:Register("font", "Roboto", [[Interface\Addons\PhreakDisplayFonts\Fonts\Roboto.ttf]]) 
PhreakDisplayFonts:Register("font", "Share Bold", [[Interface\Addons\PhreakDisplayFonts\Fonts\Share Bold.ttf]]) 
PhreakDisplayFonts:Register("font", "Share", [[Interface\Addons\PhreakDisplayFonts\Fonts\Share.ttf]]) 
PhreakDisplayFonts:Register("font", "The Godfather", [[Interface\Addons\PhreakDisplayFonts\Fonts\The Godfather.ttf]]) 
PhreakDisplayFonts:Register("font", "Vibrocentric Bold", [[Interface\Addons\PhreakDisplayFonts\Fonts\Vibrocentric Bold.ttf]]) 
PhreakDisplayFonts:Register("font", "Vibrocentric", [[Interface\Addons\PhreakDisplayFonts\Fonts\Vibrocentric.ttf]]) 
PhreakDisplayFonts:Register("font", "Waltograph Bold", [[Interface\Addons\PhreakDisplayFonts\Fonts\Waltograph Bold.ttf]]) 
PhreakDisplayFonts:Register("font", "Waltograph", [[Interface\Addons\PhreakDisplayFonts\Fonts\Waltograph.ttf]]) 
PhreakDisplayFonts:Register("font", "Yellowjacket Shadow", [[Interface\Addons\PhreakDisplayFonts\Fonts\Yellowjacket Shadow.ttf]]) 
PhreakDisplayFonts:Register("font", "Yellowjacket", [[Interface\Addons\PhreakDisplayFonts\Fonts\Yellowjacket.ttf]]) 
PhreakDisplayFonts:Register("font", "YellowJackett Expanded", [[Interface\Addons\PhreakDisplayFonts\Fonts\YellowJackett Expanded.ttf]]) 
